Repository ipfs/team-mgmt, pull requests merged in 2018-11, with the labels that each got.

#732 Create 2018-10-29--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-29--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#725 Create 2018-10-22--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-22--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#740 Create 2018-11-05--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-11-05--js-core-dev-team-weekly.md
Labels: in progress

#741 Create 2018-11-05--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-11-05--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#751 docs: Add FAQ for soln to Livestreaming not visible in IPFS Youtube Channel
  HOST_A_CALL.md
Labels: in progress

#734 Create 2018-10-29--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-29--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#763 Create 2018-11-12--all-hands.md
  meeting-notes/2018/2018-11-12--all-hands.md
Labels: in progress

#760 Move meeting notes for GUI and In Web Browsers WGs
  meeting-notes/2017/2017-03-29--in-web-browsers-standup.md
  meeting-notes/2017/2017-10-02--lab-week-discussions-on-ipfs-in-browser-extension.md
  meeting-notes/2017/2017-12-29--in-web-browsers-q1-planning-brainstorming.md
  meeting-notes/2017/2018-01-09--in-web-browsers-q1-planning-brainstorming.md
  meeting-notes/2018/2018-04-03--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-04-09--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-04-16--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-04-23--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-04-30--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-05-08--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-05-14--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-05-21--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-05-29--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-06-04--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-06-11--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-06-18--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-06-25--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-07-02--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-07-16--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-07-23--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-07-30--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-08-06--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-08-20--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-08-28--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-09-04--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-09-10--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-09-17--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-09-24--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-10-01--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-10-15--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-10-22--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-10-29--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-11-05--gui-and-in-web-browsers-weekly.md
Labels: in progress

#758 Create 2018-11-12--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-11-12--js-core-dev-team-weekly.md
Labels: in progress

#754 Adding the IPLD call
  HOST_A_CALL.md
Labels: in progress

#742 Recurrent archival of Cluster standup cryptpad
  meeting-notes/2018/2018-05-24-to-2018-10-30--cluster-meeting-archive.md
Labels: in progress

#765 Add links to IPLD and libp2p planning repositories
  README.md
Labels: in progress

#739 Proposal: Upgrade the IPFS All Hands Format
  IPFS_WEEKLY_CALL_FORMAT.md
  README.md
Labels: IPFS All Hands 🙌🏽, in progress

#771 Create 2018-11-21--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-11-21--gui-and-in-web-browsers-weekly.md
Labels: in progress

#777 IPFS Weekly notes for 11/26/2018
  meeting-notes/2018/2018-11-26--ipfs-weekly.md
Labels: in progress

#776 Update sync-labels README with better instructions
  tools/sync-labels/readme.md
Labels: in progress

#775 Create 2018-11-26--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-11-26--js-core-dev-team-weekly.md
Labels: in progress

#747 Team Roles Doc - Captain and Technical Manager definitions
  TEAM_ROLES.md
  TEAM_STRUCTURES.md
Labels: in progress

#779 Create 2018-11-26--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-11-26--go-core-dev-team-weekly.md
Labels: in progress

#781 docs: officially disband Dev Team Enablement
  TEAM_STRUCTURES.md
Labels: in progress

#778 fix: community wg will not manage social media
  TEAM_STRUCTURES.md
Labels: in progress
