Repository ipfs/team-mgmt, pull requests merged in 2018-12, with the labels that each got.

#783 docs: Instantiating the "Local Offline Collaboration" working group
  TEAM_STRUCTURES.md
Labels: in progress

#787 Create 2018-12-03--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-12-03--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#784 Create 2018-11-28--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-11-28--gui-and-in-web-browsers-weekly.md
Labels: in progress

#786 Create 2018-12-03--ipfs-weekly.md
  meeting-notes/2018/2018-12-03--ipfs-weekly.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#788 Create 2018-12-03--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-12-03--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#795 docs: Add notes for JS core dev meeting 10th December 2018
  meeting-notes/2018/2018-12-10--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#798 IPFS Weekly Call Notes for 2018-12-10
  meeting-notes/2018/2018-12-10--ipfs-weekly.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#789 Create 2018-12-05--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-12-05--gui-and-in-web-browsers-weekly.md
Labels: in progress

#797 Create 2018-12-10--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-12-10--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#807 docs: add mlists
  TEAM_STRUCTURES.md
Labels: in progress

#805 Create 2018-12-12--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/2018-12-12--gui-and-in-web-browsers-weekly.md
Labels: in progress

#811 IPFS Weekly Call Notes for 12-17-2018
  meeting-notes/2018/2018-12-17--ipfs-weekly-call.md
Labels: in progress

#812 Create 2018-12-17--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-12-17--go-core-dev-team-weekly.md
Labels: in progress

#813 docs: upgrade Weekly template
  templates/all-hands-pad-template.md
Labels: in progress

#816 Create 2018-12-19--gui-and-in-web-browsers-weekly.md
  meeting-notes/2018/Q4/2018-12-19--gui-and-in-web-browsers-weekly.md
Labels: in progress
