Repository ipfs/team-mgmt, pull requests merged in 2018-10, with the labels that each got.

#708 Create 2018-09-24--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-09-24--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#706 Create 2018-09-24--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-09-24--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#711 Create 2018-10-01--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-09-10--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-01--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#712 Add All-Hands meeting notes for 2018-10-01
  meeting-notes/2018/2018-10-01--all-hands.md
Labels: in progress

#713 docs: Team Coordination Toolkit
  TEAM_COORDINATION_TOOLKIT.md
Labels: in progress

#715 Create 2018-09-24--all-hands.md
  meeting-notes/2018/2018-09-24--all-hands.md
Labels: in progress

#710 Create 2018-10-01--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-01--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#718 Create 2018-10-15--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-15--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#717 Create roadmap-how-to.md
  ROADMAP_HOW_TO.md
Labels: in progress

#721 Roadmap diagram in img folder
  img/README.md
  img/Roadmap Components.png
Labels: in progress

#722 complete todo of inserting roadmap components img
  ROADMAP_HOW_TO.md
Labels: in progress

#723 Additional tuesday meeting notes
  meeting-notes/2018/2018-10-16--go-core-dev-hack-week.md
Labels: in progress

#726 Create 2018-10-22--all-hands.md
  meeting-notes/2018/2018-10-22--all-hands.md
Labels: in progress

#728 Add link to roadmap examples and templates
  ROADMAP_HOW_TO.md
Labels: in progress

#727 Create 2018-10-22--go-core-dev-team-weekly.md
  meeting-notes/2018/2018-10-22--go-core-dev-team-weekly.md
Labels: in progress

#735 Create 2018-10-29--all-hands.md
  meeting-notes/2018/2018-10-29--all-hands.md
Labels: IPFS All Hands 🙌🏽, in progress
