Repository ipfs/team-mgmt, pull requests merged in 2018-09, with the labels that each got.

#690 Notes from 2018-09-03 JS Core All Hands
  meeting-notes/2018/2018-09-03--all-hands.md
Labels: in progress

#691 Add recording link
  meeting-notes/2018/2018-09-03--go-all-hands.md
Labels: in progress

#692 Added youtube recording url
  meeting-notes/2018/2018-09-03--js-all-hands.md
Labels: in progress

#689 Add All-Hands meeting notes for 2018-09-03
  meeting-notes/2018/2018-09-03--all-hands.md
Labels: in progress

#694 Create 2018-09-10--all-hands.md
  meeting-notes/2018/2018-09-10--all-hands.md
Labels: in progress

#686 Create 2018-08-27--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-08-27--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#687 add go-dev meeting, 2018-08-27
  meeting-notes/2018/2018-08-27--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#701 Create 2018-09-17--all-hands.md
  meeting-notes/2018/2018-09-17--all-hands.md
Labels: in progress

#704 Add details to call-hosting guide
  guides/HOST_A_CALL.md
Labels: in progress

#695 Create 2018-09-10--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-09-10--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#696 Create 018-09-10--go-core-dev-team-weekly.md
  meeting-notes/2018/018-09-10--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#702 Create 2018-09-17--js-core-dev-team-weekly.md
  meeting-notes/2018/2018-09-17--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev
