Repository ipfs/team-mgmt, pull requests merged in 2019-05, with the labels that each got.

#822 proposal: promote Lead Maintainer Protocol to be Org wide -> Repo Lead Maintainer Protocol
  LEAD_MAINTAINER_PROTOCOL.md
Labels: P2 - Medium, in progress

#965 move infra to dev section + reorder
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#927 OKRs - 2019 Q2 JS Core
  OKR/JS_CORE.md
Labels: in progress

#954 IPFS Weekly Call Notes for April 22, 2019
  meeting-notes/2019/Q2/2019-04-22--ipfs-weekly-call.md
Labels: in progress

#966 IPFS Weekly Call Notes for 5/6
  meeting-notes/2019/Q2/2019-05-06--ipfs-weekly-call.md
Labels: in progress

#962 Create 2019-04-29--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-29--go-core-dev-team-weekly.md
Labels: in progress

#959 Create 2019-04-29--js-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-29--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#971 Update README.md
  README.md
Labels: in progress

#938 Collapse Community WG responsibilities into Project WG
  README.md
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#914 OKRs - 2019 Q2 Project WG
  OKR/PROJECT.md
Labels: in progress

#920 OKRs - 2019 Q2 DDC
  OKR/DDC.md
Labels: in progress

#802 OKRs - 2019 Q1 DDC WG
  OKR/DDC.md
Labels: P1 - High, in progress

#865 Notes for the February 4th IPFS Weekly Call
  meeting-notes/2019/Q1/2019-02-04--ipfs-weekly-call.md
Labels: blocked, in progress

#903 OKRs - 2019 Q2 Go Core Dev
  OKR/GO_CORE.md
Labels: in progress

#967 JS Core dev meeting notes 2019-05-06
  meeting-notes/2019/Q2/2019-05-06--js-core-dev-team-weekly.md
Labels: ⚡️ⒿⓈ Core Dev

#968 Create 2019-05-06--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-05-06--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#973 May 13th IPFS Weekly Call
  meeting-notes/2019/Q2/2019-05-13--ipfs-weekly-call.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#957 docs: remove Waffle.io
  README.md
Labels: in progress

#969 Create 2019-05-08--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/2019-05-08--gui-and-in-web-browsers-weekly.md
Labels: in progress

#974 Create 2019-04-13--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-13--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#976 IPFS Weekly Notes for May 20th
  meeting-notes/2019/Q2/2019-05-20--ipfs-weekly-call.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#978 Create 2019-05-20--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-05-20--go-core-dev-team-weekly.md
Labels: 💫 Golang Core Dev

#972 Create 2019-05-13--js-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-05-13--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#983 Create 2019-05-27--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-05-27--go-core-dev-team-weekly.md
Labels: 💫 Golang Core Dev
