Repository ipfs/team-mgmt, pull requests merged in 2019-04, with the labels that each got.

#912 Create 2019-03-25--js-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-03-25--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#904 Create 2019-03-18--js-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-03-18--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#895 Add JS Dev weekly 2019-03-11 meeting notes
  meeting-notes/2019/Q1/2019-03-11--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#913 Create 2019-03-25--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-03-25--go-core-dev-team-weekly.md
Labels: in progress

#925 update all hands time in UTC
  templates/all-hands-issue-template.md
Labels: in progress

#928 Research Group --> Special Interest Group
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#929 can haz mailing list!
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#908 Create 2019-03-20--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-03-20--gui-and-in-web-browsers-weekly.md
Labels: in progress

#923 Create 2019-04-01--js-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-01--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#933 Add cross team updates section to the template
  templates/CORE_DEV_WEEKLY.md
Labels: in progress

#924 Create 2019-04-01--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-01--go-core-dev-team-weekly.md
Labels: in progress

#931 Create 2019-04-03--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/2019-04-03--gui-and-in-web-browsers-weekly.md
Labels: in progress

#940 Update Captain and Project Lead responsibilities to accurately reflect current expectations and asks
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#934 Adding notes of JS Core Dev meeting 2019-04-08
  meeting-notes/2019/Q2/2019-04-08--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#915 OKRs - 2019 Q2 Locol
  OKR/LOCOL.md
Labels: in progress

#918 OKRs - 2019 Q2 Package Managers WG
  OKR/PACKAGE-MANAGERS.md
Labels: in progress

#942 Create 2019-04-15--ipfs-weekly-call.md
  meeting-notes/2019/Q2/2019-04-15--ipfs-weekly-call.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#916 docs: make package managers weekly notes public
  meeting-notes/2019/Q1/2019-02-12--package-managers-weekly.md
  meeting-notes/2019/Q1/2019-02-19--package-managers-weekly.md
  meeting-notes/2019/Q1/2019-03-05--package-managers-weekly.md
  meeting-notes/2019/Q1/2019-03-12--package-managers-weekly.md
Labels: in progress

#939 Add notes from 4-11-19 Community WG call
  meeting-notes/2019/Q2/2019-04-11--ipfs-community-wg-weekly.md
Labels: in progress

#935 Create 2019-04-08--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-08--go-core-dev-team-weekly.md
Labels: in progress

#937 Create 2019-04-10--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/2019-04-10--gui-and-in-web-browsers-weekly.md
Labels: in progress

#943 Create 2019-04-15--js-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-15--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#950 Replace monthly "5 min presentations" with show and tell
  IPFS_WEEKLY_CALL.md
Labels: in progress

#944 Create 2019-04-15--go-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-15--go-core-dev-te``am-weekly.md
Labels: in progress

#949 Rename mislabeled call notes
  meeting-notes/2019/Q1/2019-01-21--ipfs-weekly-call.md
  meeting-notes/2019/Q1/2019-01-28--ipfs-weekly-call.md
Labels: in progress

#945 Create 2019-04-17--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/https:/github.com/ipfs/team-mgmt/blob/master/meeting-notes/2019/Q2/2019-04-17--gui-and-in-web-browsers-weekly.md
Labels: in progress

#951 Updated Issue Template
  templates/all-hands-issue-template.md
Labels: in progress

#952 Create 2019-04-22--js-core-dev-team-weekly.md
  meeting-notes/2019/Q2/2019-04-22--js-core-dev-team-weekly.md
Labels: in progress

#956 Reclassify some working groups and update membership info
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#958 feat: add Github Teams for each Working Group
  TEAMS_ROLES_STRUCTURES.md
Labels: in progress

#948 Create 2019-04-07--ipns.md
  meeting-notes/2019/Q2/2019-04-17--ipns.md
Labels: in progress

#955 Create 2019-04-24--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/2019-04-24--gui-and-in-web-browsers-weekly.md
Labels: in progress

#961 Delete 2019-04-17--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/https:/github.com/ipfs/team-mgmt/blob/master/meeting-notes/2019/Q2/2019-04-17--gui-and-in-web-browsers-weekly.md
Labels: in progress

#960 Create 2019-04-17--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q2/2019-04-17--gui-and-in-web-browsers-weekly.md
Labels: in progress

#953 Create 2019-04-22--go-core-dev-team-weekly.md
  2019-04-22--go-core-dev-team-weekly.md
Labels: in progress
