Repository ipfs/team-mgmt, pull requests merged in 2019-02, with the labels that each got.

#858 IPFS Weekly Community Sync Notes January 29th
  meeting-notes/2019/Q1/2019-01-31--ipfs-community-wg-weekly.md
Labels: in progress

#853 Create 2019-01-28--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-01-28--go-core-dev-team-weekly.md
Labels: in progress

#856 Add 2019-01-30--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-01-30--gui-and-in-web-browsers-weekly.md
Labels: in progress

#840 Create 2018-12-12-to-2019-01-15--cluster-meeting-archive.md
  meeting-notes/2019/Q1/2018-12-12-to-2019-01-15--cluster-meeting-archive.md
Labels: in progress

#859 Create 2019-02-04--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-02-04--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#860 Create 2019-02-04--js-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-02-04--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#799 OKRs - 2019 Q1 JS Core WG
  OKR/JS_CORE.md
Labels: P1 - High, in progress

#803 OKRs - 2019 Q1 Local Offline Collab WG
  OKR/LOCOL.md
Labels: P1 - High, in progress

#806 OKRs - 2019 Q1 Infra WG
  OKR/INFRA.md
Labels: P1 - High, in progress

#862 Link to Q1 2019 OKRs
  OKR/JS_CORE.md
Labels: in progress

#864 Rename 2019-1-21--ipfs-community-wg-weekly.md to 2019-01-21--ipfs-com…
  meeting-notes/2019/Q1/2019-01-21--ipfs-community-wg-weekly.md
Labels: in progress

#863 Rename 2019-1-28--ipfs-community-wg-weekly.md to 2019-01-28--ipfs-com…
  meeting-notes/2019/Q1/2019-01-28--ipfs-community-wg-weekly.md
Labels: in progress

#800 OKRs - 2019 Q1 Community WG
  OKR/COMMUNITY.md
Labels: P1 - High, in progress

#867 Create 2019-02-06--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-02-06--gui-and-in-web-browsers-weekly.md
Labels: in progress

#861 OKRs - 2019 Q1 Cluster WG
  OKR/CLUSTER.md
Labels: in progress

#793 OKRs - 2019 Q1 Project WG
  OKR/PROJECT.md
Labels: P1 - High, in progress

#870 Create 2019-02-11--js-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-02-11--js-core-dev-team-weekly.md
Labels: ⚡️ⒿⓈ Core Dev

#869 Merge Team Roles & Structures docs into a single unified source of structure :)
  README.md
  TEAMS_ROLES_STRUCTURES.md
  TEAM_ROLES.md
Labels: in progress

#814 OKRs - 2019 Q1 DDS WG
  OKR/DDS.md
Labels: P1 - High, in progress

#872 Notes for February 11th IPFS Weekly Meeting
  meeting-notes/2019/Q1/2019-02-11--ipfs-weekly-call.md
Labels: in progress

#804 OKRs - 2019 Q1 Web Browsers WG
  OKR/WB.md
Labels: P1 - High, in progress

#808 OKRs - 2019 Q1 GUI WG
  OKR/GUI.md
Labels: P1 - High, in progress

#876 February 18th IPFS Weekly Call Notes
  meeting-notes/2019/Q1/2019-02-18--ipfs-weekly-call.md
Labels: in progress

#875 Create 2019-02-18--js-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-02-18--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#874 Create 2019-02-13--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-02-13--gui-and-in-web-browsers-weekly.md
Labels: in progress

#878 2019-02-18--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-02-18--go-core-dev-team-weekly.md
Labels: in progress

#868 Create 2019-02-07--ipfs-community-wg-weekly.md
  meeting-notes/2019/Q1/2019-02-07--ipfs-community-wg-weekly.md
Labels: in progress

#883 IPFS Weekly Call notes for February 25, 2019
  meeting-notes/2019/Q1/2019-02-25--ipfs-weekly-call.md
Labels: in progress
