Repository ipfs/team-mgmt, pull requests merged in 2019-01, with the labels that each got.

#819 docs: import the Lead Maintainer Protocol
  LEAD_MAINTAINER_PROTOCOL.md
Labels: in progress

#818 docs: add reference to the Kanbans we use
  KANBAN.md
  MGMT_GOLANG_CORE_DEV.md
  README.md
Labels: in progress

#826 Give an update to sync-labels tool
  .gitignore
  tools/sync-labels/config.json
  tools/sync-labels/labels.json
  tools/sync-labels/orgs.json
  tools/sync-labels/out/.gitkeep
  tools/sync-labels/package-lock.json
  tools/sync-labels/package.json
  tools/sync-labels/readme.md
  tools/sync-labels/src/create-config.js
  tools/sync-labels/src/fetch-repos.js
Labels: in progress

#825 Create 2019-01-03--ipfs-community-wg-weekly.md
  meeting-notes/2019/Q1/2019-01-03--ipfs-community-wg-weekly.md
Labels: in progress

#829 Create 2019-01-07--js-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-01-07--js-core-dev-team-weekly.md
Labels: in progress, ⚡️ⒿⓈ Core Dev

#831 Add Working Group Mailing Lists
  TEAM_STRUCTURES.md
Labels: in progress

#820 All the planning in one picture
  README.md
  img/ipfs-org-planning-one-picture.jpeg
Labels: in progress

#821 Create 2019-01-02--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-01-02--gui-and-in-web-browsers-weekly.md
Labels: in progress

#828 IPFS Weekly Call Notes 2019-01-07
  meeting-notes/2019/Q1/2019-01-07--ipfs-weekly-call.md
Labels: in progress

#835 docs: add Kanban resources
  DISTRIBUTED_TEAMS.md
Labels: in progress

#832 Create 2019-01-09--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-01-09--gui-and-in-web-browsers-weekly.md
Labels: in progress

#833 Create 2019-01-10--ipfs-community-wg-weekly.md
  meeting-notes/2019/Q1/2019-01-10--ipfs-community-wg-weekly.md
Labels: in progress

#839 January 14th 2018 IPFS Weekly Call
  meeting-notes/2019/Q1/2019-01-14--ipfs-weekly-call.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#844 IPFS Weekly Call notes for 2019-21-1
  meeting-notes/2019/Q1/2019-1-21--ipfs-community-wg-weekly.md
Labels: in progress, 🙌🏽 IPFS Weekly Call 📞

#841 Create 2019-01-16--gui-and-in-web-browsers-weekly.md
  meeting-notes/2019/Q1/2019-01-16--gui-and-in-web-browsers-weekly.md
Labels: in progress, 📞 Calls (Sync Time)

#848 Notes for the 2019-01-24 Community WG
  meeting-notes/2019/Q1/2019-01-24--ipfs-community-wg-weekly.md
Labels: in progress

#845 Create 2019-01-21--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-01-21--go-core-dev-team-weekly.md
Labels: in progress

#838 Create 2019-01-14--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-01-14--go-core-dev-team-weekly.md
Labels: in progress

#830 Create 2019-01-07--go-core-dev-team-weekly.md
  meeting-notes/2019/Q1/2019-01-07--go-core-dev-team-weekly.md
Labels: in progress, 💫 Golang Core Dev

#854 Notes for the IPFS Community Call 2019-1-28
  meeting-notes/2019/Q1/2019-1-28--ipfs-community-wg-weekly.md
Labels: in progress
